name: "New movies"
description: "Checks a market for newly added movies."
inputs:
  alamoMarket:
    description: "Alamo market (e.g. Los Angeles)"
    required: true
outputs:
  movies:
    description: "Newly added movies"
    value: ${{ steps.get-new-movies.outputs.value }}
runs:
  using: "composite"
  steps:
    - id: get-new-movies
      run: |
        r=$(yarn new-movies ${{ inputs.alamoMarket }})
        r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
        r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
        r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
        r="${r//$'\''/'%E2%80%99'}"                       # Multiline escape sequences for `'`
        r="${r//$':'/'%3A'}"                              # Multiline escape sequences for ':'
        echo "::set-output name=value::$r"
      shell: bash
