inputs:
  alamoMarket:
    description: "Alamo market (e.g. Los Angeles)"
    required: true
outputs:
  movies:
    description: "Newly added movies"
    value: ${{ steps.get-new-movies.outputs.movies }}
runs:
  using: "composite"
  steps:
    - id: get-new-movies
      run: echo "::set-output name=movies::$(yarn new-movies ${{ inputs.alamoMarket }})"
      shell: bash
