inputs:
  alamoMarket:
    description: "Alamo market (e.g. Los Angeles)"
    required: true
outputs:
  screenings:
    description: "Newly added screenings"
    value: ${{ steps.get-new-screenings.outputs.screenings }}
runs:
  using: "composite"
  steps:
    - id: get-new-screenings
      run: echo "::set-output name=screenings::$(yarn new-screenings ${{ inputs.alamoMarket }})"
      shell: bash
