name: Check for new LA movies
on:
  push:
  schedule:
    - cron: "6 * * * *" # hourly, 6 mins past the hour
jobs:
  check-movies-los-angeles:
    runs-on: ubuntu-latest
    steps:
      # Checks out code from Github.
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Fetch latest movie data for market.
        run: yarn fetch los-angeles
      - name: Check for new movies.
        id: new-movies
        uses: ./.github/actions/new-movies
        with:
          alamoMarket: los-angeles
      - name: Check for new screenings.
        id: new-screenings
        uses: ./.github/actions/new-screenings
        with:
          alamoMarket: los-angeles
      - run: echo new-movies ${{ steps.new-movies.outputs.movies }}
        shell: bash
      - name: (on movie/screenings add) Update readme for market.
        if: steps.new-movies.outputs.movies != '' || steps.new-screenings.outputs.screenings != ''
        run: yarn update-readme los-angeles
      - name: (on movie/screenings add) Update movie cache.
        if: steps.new-movies.outputs.movies != '' || steps.new-screenings.outputs.screenings != ''
        run: yarn cleanup los-angeles
      - name: (on movie/screenings add) Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.SMTP_SERVER}}
          server_port: ${{secrets.SMTP_PORT}}
          username: ${{secrets.SMTP_USER}}
          password: ${{secrets.SMTP_PASS}}
          subject: "New Alamo screenings: ${{steps.new-movies.outputs.movies}}"
          to: david.b.calhoun@gmail.com
          from: '"Davids Alamo Bot" <david.b.calhoun@gmail.com>'
          secure: true
          html_body: file://./los-angeles.md
          reply_to: david.b.calhoun@gmail.com
          convert_markdown: true
          priority: low
      - name: (on movie/screenings add) Check in new movies to the repo.
        uses: test-room-7/action-update-file@v1
        if: steps.new-movies.outputs.movies != '' || steps.new-screenings.outputs.screenings != ''
        with:
          file-path: |
            data/*.json
            markets/*.md
          commit-msg: Bot - adding new movies/screenings
          github-token: ${{ secrets.GITHUB_TOKEN }}
